// Generated by tools/import_brotato_presentation.py. Do not edit by hand.
#pragma once
#include "Render/Public/Sprite/sprite_animation.h"
#include "Brotato/Public/weapon_definitions.h"
#include <array>

namespace Brotato {
struct AnimatedNode {
    int parent; Render::Animation::Pose base; Image image; bool visible;
    glm::vec2 size, pivot; glm::vec4 tint; int order;
};
inline const std::array<AnimatedNode, 9> PlayerNodes{{
    // Animator root
    {-1, {{0.0f, 0.0f}, {1.0f, 1.0f}, 0.0f, 1.0f}, Image::Player, false, {1.0f, 1.0f}, {0.5f, 0.5f}, {1.0f, 1.0f, 1.0f, 1.0f}, 0},
    // Player_Body_All
    {0, {{0.0f, 0.25f}, {1.0f, 1.0f}, 0.0f, 1.0f}, Image::Player, false, {1.0f, 1.0f}, {0.5f, 0.5f}, {1.0f, 1.0f, 1.0f, 1.0f}, 0},
    // Player_Body_All/Mark
    {1, {{0.0f, -0.326f}, {1.0f, 1.0f}, 0.0f, 1.0f}, Image::PlayerMark, true, {0.679465f, 0.3584776f}, {0.51471746f, 0.49999994f}, {0.44705883f, 1.0f, 0.9490196f, 0.4509804f}, -1},
    // Player_Body_All/Body
    {1, {{0.0f, 0.0f}, {1.0f, 1.0f}, 0.0f, 1.0f}, Image::PlayerBody, true, {0.6289713f, 0.72897125f}, {0.5083419f, 0.46536648f}, {1.0f, 1.0f, 1.0f, 1.0f}, -1},
    // Player_Body_All/Body/Itemes
    {3, {{-0.0010128f, 0.018993f}, {-0.7974548f, 0.7974548f}, 0.0f, 1.0f}, Image::Player, true, {0.7684776f, 0.8789713f}, {0.5065064f, 0.49971917f}, {1.0f, 1.0f, 1.0f, 1.0f}, 0},
    // Player_Body_All/Shadow
    {1, {{0.0f, -0.32599998f}, {1.0f, -0.3f}, 0.0f, 1.0f}, Image::PlayerShadow, true, {0.6289713f, 0.72897125f}, {0.5083419f, 0.46536648f}, {0.0f, 0.0f, 0.0f, 0.4509804f}, -1},
    // Player_Body_All/Player_Legs
    {1, {{0.0f, 0.063999996f}, {1.25f, 1.25f}, 0.0f, 1.0f}, Image::Player, false, {1.0f, 1.0f}, {0.5f, 0.5f}, {1.0f, 1.0f, 1.0f, 1.0f}, 0},
    // Player_Body_All/Player_Legs/Leg_r
    {6, {{-0.18f, -0.25f}, {1.0f, 1.0f}, 0.0f, 1.0f}, Image::PlayerLegRight, true, {0.2188657f, 0.28946497f}, {0.45455655f, 0.5172733f}, {1.0f, 1.0f, 1.0f, 1.0f}, -1},
    // Player_Body_All/Player_Legs/Leg_L
    {6, {{0.18f, -0.25f}, {1.0f, 1.0f}, 0.0f, 1.0f}, Image::PlayerLegLeft, true, {0.20897127f, 0.28921932f}, {0.52510816f, 0.5168632f}, {1.0f, 1.0f, 1.0f, 1.0f}, -1},
}};
inline const std::array<AnimatedNode, 3> EnemyNodes{{
    // Animator root
    {-1, {{0.0f, 0.0f}, {1.0f, 1.0f}, 0.0f, 1.0f}, Image::Enemy, false, {1.0f, 1.0f}, {0.5f, 0.5f}, {1.0f, 1.0f, 1.0f, 1.0f}, 0},
    // Monster_All
    {0, {{0.0f, 0.25f}, {1.0f, 1.0f}, 0.0f, 1.0f}, Image::Enemy, false, {1.0f, 1.0f}, {0.5f, 0.5f}, {1.0f, 1.0f, 1.0f, 1.0f}, 0},
    // Monster_All/Monster
    {1, {{0.0f, 0.0f}, {1.0f, 1.0f}, 0.0f, 1.0f}, Image::Enemy, true, {0.76880974f, 0.8984776f}, {0.49371243f, 0.5333898f}, {1.0f, 1.0f, 1.0f, 1.0f}, 10},
}};
inline const std::array<glm::vec2, 5> CharacterPivots{{
    {0.5065064f, 0.49971917f}, // well_rounded
    {0.5065064f, 0.49971917f}, // brawler
    {0.5065064f, 0.49971917f}, // crazy
    {0.5128456f, 0.49971917f}, // ranger
    {0.4477927f, 0.5218909f}, // mage
}};
inline constexpr std::array<Render::Animation::Key, 2> PlayerIdleKeys0{{
    {0.0f, 0.0f, 0.0f, 0.0f},
    {1.0333333f, 0.0f, 0.0f, 0.0f},
}};
inline constexpr std::array<Render::Animation::Key, 2> PlayerIdleKeys1{{
    {0.0f, 0.0f, 0.0f, 0.0f},
    {1.0333333f, 0.0f, 0.0f, 0.0f},
}};
inline constexpr std::array<Render::Animation::Key, 2> PlayerIdleKeys2{{
    {0.0f, 0.0f, 0.0f, 0.0f},
    {1.0333333f, 0.0f, 0.0f, 0.0f},
}};
inline constexpr std::array<Render::Animation::Key, 3> PlayerIdleKeys3{{
    {0.0f, 0.0f, 0.0f, 0.0f},
    {0.5f, 0.0f, 0.0f, 0.0f},
    {1.0f, 0.0f, 0.0f, 0.0f},
}};
inline constexpr std::array<Render::Animation::Key, 3> PlayerIdleKeys4{{
    {0.0f, 0.25f, 0.0f, 0.0f},
    {0.5f, 0.2f, 0.0f, 0.0f},
    {1.0f, 0.25f, 0.0f, 0.0f},
}};
inline constexpr std::array<Render::Animation::Key, 2> PlayerIdleKeys5{{
    {0.0f, 0.18f, 0.0f, 0.0f},
    {1.0333333f, 0.18f, 0.0f, 0.0f},
}};
inline constexpr std::array<Render::Animation::Key, 2> PlayerIdleKeys6{{
    {0.0f, -0.25f, 0.0f, 0.0f},
    {1.0333333f, -0.25f, 0.0f, 0.0f},
}};
inline constexpr std::array<Render::Animation::Key, 2> PlayerIdleKeys7{{
    {0.0f, -0.18f, 0.0f, 0.0f},
    {1.0333333f, -0.18f, 0.0f, 0.0f},
}};
inline constexpr std::array<Render::Animation::Key, 2> PlayerIdleKeys8{{
    {0.0f, -0.25f, 0.0f, 0.0f},
    {1.0333333f, -0.25f, 0.0f, 0.0f},
}};
inline constexpr std::array<Render::Animation::Key, 3> PlayerIdleKeys9{{
    {0.0f, 1.0f, 0.0f, 0.0f},
    {0.5f, 1.15f, 0.0f, 0.0f},
    {1.0f, 1.0f, 0.0f, 0.0f},
}};
inline constexpr std::array<Render::Animation::Key, 3> PlayerIdleKeys10{{
    {0.0f, 1.0f, 0.0f, 0.0f},
    {0.5f, 0.85f, 0.0f, 0.0f},
    {1.0f, 1.0f, 0.0f, 0.0f},
}};
inline constexpr std::array<Render::Animation::Key, 2> PlayerIdleKeys11{{
    {0.0f, 1.0f, 0.0f, 0.0f},
    {1.0333333f, 1.0f, 0.0f, 0.0f},
}};
inline constexpr std::array<Render::Animation::Key, 2> PlayerIdleKeys12{{
    {0.0f, 1.0f, 0.0f, 0.0f},
    {1.0333333f, 1.0f, 0.0f, 0.0f},
}};
inline const std::array<Render::Animation::Track, 13> PlayerIdleTracks{{
    {7, Render::Animation::Channel::AngleDegrees, PlayerIdleKeys0},
    {8, Render::Animation::Channel::AngleDegrees, PlayerIdleKeys1},
    {3, Render::Animation::Channel::AngleDegrees, PlayerIdleKeys2},
    {1, Render::Animation::Channel::PositionX, PlayerIdleKeys3},
    {1, Render::Animation::Channel::PositionY, PlayerIdleKeys4},
    {8, Render::Animation::Channel::PositionX, PlayerIdleKeys5},
    {8, Render::Animation::Channel::PositionY, PlayerIdleKeys6},
    {7, Render::Animation::Channel::PositionX, PlayerIdleKeys7},
    {7, Render::Animation::Channel::PositionY, PlayerIdleKeys8},
    {1, Render::Animation::Channel::ScaleX, PlayerIdleKeys9},
    {1, Render::Animation::Channel::ScaleY, PlayerIdleKeys10},
    {7, Render::Animation::Channel::ScaleX, PlayerIdleKeys11},
    {7, Render::Animation::Channel::ScaleY, PlayerIdleKeys12},
}};
inline const Render::Animation::Clip PlayerIdle{1.0f, true, PlayerIdleTracks};
inline constexpr std::array<Render::Animation::Key, 7> PlayerMoveKeys0{{
    {0.0f, -61.3f, 0.0f, 0.0f},
    {0.1f, -105.0f, 0.00015258789f, 0.0f},
    {0.2f, 47.0f, -0.00030517578f, 0.0f},
    {0.3f, 33.0f, -280.0f, -280.0f},
    {0.4f, -29.0f, -240.00002f, -240.00002f},
    {0.5f, -41.0f, -161.50003f, -161.49998f},
    {0.6f, -61.3f, 1.9073483e-05f, 0.0f},
}};
inline constexpr std::array<Render::Animation::Key, 7> PlayerMoveKeys1{{
    {0.0f, 29.0f, 0.0f, 0.0f},
    {0.1f, -12.0f, -484.9999f, -485.0f},
    {0.2f, -68.0f, -159.99995f, -159.99998f},
    {0.3f, -76.0f, -160.0f, -160.0f},
    {0.4f, -109.0f, 7.629395e-05f, 0.0f},
    {0.5f, 14.0f, 299.99973f, 299.99997f},
    {0.6f, 29.0f, 1.9073483e-05f, 0.0f},
}};
inline constexpr std::array<Render::Animation::Key, 7> PlayerMoveKeys2{{
    {0.0f, 0.0f, 0.0f, 0.0f},
    {0.1f, 0.0f, 0.0f, 0.0f},
    {0.2f, 0.0f, 0.0f, 0.0f},
    {0.3f, 0.0f, 0.0f, 0.0f},
    {0.4f, 0.0f, 0.0f, 0.0f},
    {0.5f, 0.0f, 0.0f, 0.0f},
    {0.6f, 0.0f, 0.0f, 0.0f},
}};
inline constexpr std::array<Render::Animation::Key, 7> PlayerMoveKeys3{{
    {0.0f, 0.25f, 0.0f, 0.0f},
    {0.1f, 0.16f, 2.9802322e-07f, 0.0f},
    {0.2f, 0.3f, -2.9802322e-07f, 0.0f},
    {0.3f, 0.22f, -0.7f, -0.70000005f},
    {0.4f, 0.16f, 0.0f, 0.0f},
    {0.5f, 0.3f, -2.9802325e-07f, 0.0f},
    {0.6f, 0.25f, 1.4901158e-07f, 0.0f},
}};
inline constexpr std::array<Render::Animation::Key, 7> PlayerMoveKeys4{{
    {0.0f, 0.23f, 0.0f, 0.0f},
    {0.1f, 0.142f, -1.76f, -1.7600001f},
    {0.2f, -0.212f, -0.04000008f, -0.040000413f},
    {0.3f, -0.214f, 0.0f, 0.0f},
    {0.4f, -0.196f, 0.36000016f, 0.36000016f},
    {0.5f, 0.095f, 2.0050004f, 2.0049999f},
    {0.6f, 0.205f, 7.450579e-08f, 0.0f},
}};
inline constexpr std::array<Render::Animation::Key, 7> PlayerMoveKeys5{{
    {0.0f, -0.234f, 0.0f, 0.0f},
    {0.1f, -0.26f, 7.4505806e-08f, 0.0f},
    {0.2f, -0.254f, -1.8626451e-08f, 0.0f},
    {0.3f, -0.26f, 0.0f, 0.0f},
    {0.4f, -0.22f, -7.450581e-08f, 0.0f},
    {0.5f, -0.27f, 1.4901163e-07f, 0.0f},
    {0.6f, -0.22f, -1.4901158e-07f, 0.0f},
}};
inline constexpr std::array<Render::Animation::Key, 7> PlayerMoveKeys6{{
    {0.0f, -0.187f, 0.0f, 0.0f},
    {0.1f, -0.19f, 9.313226e-09f, 0.0f},
    {0.2f, 0.195f, 0.07999897f, 0.08000041f},
    {0.3f, 0.199f, 0.0f, 0.0f},
    {0.4f, 0.142f, -1.14f, -1.14f},
    {0.5f, -0.098f, -1.6449995f, -1.645f},
    {0.6f, -0.187f, -3.7252896e-08f, 0.0f},
}};
inline constexpr std::array<Render::Animation::Key, 7> PlayerMoveKeys7{{
    {0.0f, -0.25f, 0.0f, 0.0f},
    {0.1f, -0.22f, 0.0f, 0.0f},
    {0.2f, -0.23200002f, -0.19999991f, -0.19999994f},
    {0.3f, -0.26f, 3.72529e-08f, 0.0f},
    {0.4f, -0.26f, 0.0f, 0.0f},
    {0.5f, -0.28f, 7.450581e-08f, 0.0f},
    {0.6f, -0.25f, -7.450579e-08f, 0.0f},
}};
inline constexpr std::array<Render::Animation::Key, 7> PlayerMoveKeys8{{
    {0.0f, 1.0f, 0.0f, 0.0f},
    {0.1f, 1.2f, -5.9604645e-07f, 0.0f},
    {0.2f, 0.9f, 5.9604645e-07f, 0.0f},
    {0.3f, 1.0f, 1.5000004f, 1.5000004f},
    {0.4f, 1.2f, -2.9802325e-07f, 0.0f},
    {0.5f, 0.9f, 1.192093e-06f, 0.0f},
    {0.6f, 1.0f, -2.9802317e-07f, 0.0f},
}};
inline constexpr std::array<Render::Animation::Key, 7> PlayerMoveKeys9{{
    {0.0f, 1.0f, 0.0f, 0.0f},
    {0.1f, 0.8f, 5.9604645e-07f, 0.0f},
    {0.2f, 1.1f, -5.9604645e-07f, 0.0f},
    {0.3f, 1.0f, -1.4999999f, -1.5f},
    {0.4f, 0.8f, 2.9802325e-07f, 0.0f},
    {0.5f, 1.1f, -5.960465e-07f, 0.0f},
    {0.6f, 1.0f, 2.9802317e-07f, 0.0f},
}};
inline constexpr std::array<Render::Animation::Key, 2> PlayerMoveKeys10{{
    {0.0f, -1.0f, 0.0f, 0.0f},
    {0.6333333f, -1.0f, 0.0f, 0.0f},
}};
inline constexpr std::array<Render::Animation::Key, 2> PlayerMoveKeys11{{
    {0.0f, 1.0f, 0.0f, 0.0f},
    {0.6333333f, 1.0f, 0.0f, 0.0f},
}};
inline const std::array<Render::Animation::Track, 12> PlayerMoveTracks{{
    {7, Render::Animation::Channel::AngleDegrees, PlayerMoveKeys0},
    {8, Render::Animation::Channel::AngleDegrees, PlayerMoveKeys1},
    {1, Render::Animation::Channel::PositionX, PlayerMoveKeys2},
    {1, Render::Animation::Channel::PositionY, PlayerMoveKeys3},
    {8, Render::Animation::Channel::PositionX, PlayerMoveKeys4},
    {8, Render::Animation::Channel::PositionY, PlayerMoveKeys5},
    {7, Render::Animation::Channel::PositionX, PlayerMoveKeys6},
    {7, Render::Animation::Channel::PositionY, PlayerMoveKeys7},
    {1, Render::Animation::Channel::ScaleX, PlayerMoveKeys8},
    {1, Render::Animation::Channel::ScaleY, PlayerMoveKeys9},
    {7, Render::Animation::Channel::ScaleX, PlayerMoveKeys10},
    {7, Render::Animation::Channel::ScaleY, PlayerMoveKeys11},
}};
inline const Render::Animation::Clip PlayerMove{0.6f, true, PlayerMoveTracks};
inline constexpr std::array<Render::Animation::Key, 2> EnemyMoveKeys0{{
    {0.0f, 0.0f, 0.0f, 0.0f},
    {1.0333333f, 0.0f, 0.0f, 0.0f},
}};
inline constexpr std::array<Render::Animation::Key, 3> EnemyMoveKeys1{{
    {0.0f, 0.0f, 0.0f, 0.0f},
    {0.5f, 0.0f, 0.0f, 0.0f},
    {1.0f, 0.0f, 0.0f, 0.0f},
}};
inline constexpr std::array<Render::Animation::Key, 3> EnemyMoveKeys2{{
    {0.0f, 0.25f, 0.0f, 0.0f},
    {0.5f, 0.225f, 0.0f, 0.0f},
    {1.0f, 0.25f, 0.0f, 0.0f},
}};
inline constexpr std::array<Render::Animation::Key, 3> EnemyMoveKeys3{{
    {0.0f, 1.0f, 0.0f, 0.0f},
    {0.5f, 1.15f, 0.0f, 0.0f},
    {1.0f, 1.0f, 0.0f, 0.0f},
}};
inline constexpr std::array<Render::Animation::Key, 3> EnemyMoveKeys4{{
    {0.0f, 1.0f, 0.0f, 0.0f},
    {0.5f, 0.85f, 0.0f, 0.0f},
    {1.0f, 1.0f, 0.0f, 0.0f},
}};
inline const std::array<Render::Animation::Track, 5> EnemyMoveTracks{{
    {1, Render::Animation::Channel::AngleDegrees, EnemyMoveKeys0},
    {1, Render::Animation::Channel::PositionX, EnemyMoveKeys1},
    {1, Render::Animation::Channel::PositionY, EnemyMoveKeys2},
    {1, Render::Animation::Channel::ScaleX, EnemyMoveKeys3},
    {1, Render::Animation::Channel::ScaleY, EnemyMoveKeys4},
}};
inline const Render::Animation::Clip EnemyMove{1.0f, true, EnemyMoveTracks};
inline constexpr std::array<Render::Animation::Key, 2> EnemyDeathKeys0{{
    {0.0f, 0.0f, 0.0f, 0.0f},
    {0.5f, -360.0f, 0.0f, 0.0f},
}};
inline constexpr std::array<Render::Animation::Key, 2> EnemyDeathKeys1{{
    {0.0f, 1.0f, 0.0f, 0.0f},
    {0.5f, 0.0f, 0.0f, 0.0f},
}};
inline constexpr std::array<Render::Animation::Key, 2> EnemyDeathKeys2{{
    {0.0f, 1.0f, 0.0f, 0.0f},
    {0.5f, 0.0f, 0.0f, 0.0f},
}};
inline const std::array<Render::Animation::Track, 3> EnemyDeathTracks{{
    {1, Render::Animation::Channel::AngleDegrees, EnemyDeathKeys0},
    {1, Render::Animation::Channel::ScaleX, EnemyDeathKeys1},
    {1, Render::Animation::Channel::ScaleY, EnemyDeathKeys2},
}};
inline const Render::Animation::Clip EnemyDeath{0.5f, false, EnemyDeathTracks};
inline constexpr std::array<Render::Animation::Key, 2> DamageTextKeys0{{
    {0.0f, -0.039f, 0.0f, 0.0f},
    {0.48333332f, -0.118f, 0.0f, 0.0f},
}};
inline constexpr std::array<Render::Animation::Key, 2> DamageTextKeys1{{
    {0.0f, -0.758f, 0.0f, 0.0f},
    {0.48333332f, 0.194f, 0.0f, 0.0f},
}};
inline const std::array<Render::Animation::Track, 2> DamageTextTracks{{
    {0, Render::Animation::Channel::PositionX, DamageTextKeys0},
    {0, Render::Animation::Channel::PositionY, DamageTextKeys1},
}};
inline const Render::Animation::Clip DamageText{0.48333332f, false, DamageTextTracks};
inline constexpr std::array<Render::Animation::Key, 2> MuzzleFlashKeys0{{
    {0.0f, 0.094f, 0.0f, 0.0f},
    {0.06666667f, 0.466f, 0.0f, 0.0f},
}};
inline constexpr std::array<Render::Animation::Key, 2> MuzzleFlashKeys1{{
    {0.0f, 0.025f, 0.0f, 0.0f},
    {0.06666667f, 0.025f, 0.0f, 0.0f},
}};
inline constexpr std::array<Render::Animation::Key, 3> MuzzleFlashKeys2{{
    {0.0f, 1.0f, 0.0f, 0.0f},
    {0.05f, 1.0f, 0.0f, 0.0f},
    {0.06666667f, 0.0f, 0.0f, 0.0f},
}};
inline const std::array<Render::Animation::Track, 3> MuzzleFlashTracks{{
    {0, Render::Animation::Channel::PositionX, MuzzleFlashKeys0},
    {0, Render::Animation::Channel::PositionY, MuzzleFlashKeys1},
    {0, Render::Animation::Channel::Opacity, MuzzleFlashKeys2},
}};
inline const Render::Animation::Clip MuzzleFlash{0.06666667f, false, MuzzleFlashTracks};
inline const Render::Animation::Pose DamageTextBase{{-.039f, -.758f}, {1.f, 1.f}, 0.f, 1.f};
inline const glm::vec2 DamageTextParentOffset{-0.003f, 0.972f};
inline constexpr float DamageTextFontSize = .25f;
} // namespace Brotato
