// Generated by tools/import_brotato_assets.py. Do not edit by hand.
#pragma once
#include <array>
#include <cstddef>
#include <glm/glm.hpp>

namespace Brotato {
struct CharacterDefinition { const char* id; const char* name; const char* image; glm::vec2 size; };
inline const std::array<CharacterDefinition, 5> Characters{{
    {"well_rounded", "Well-Rounded", "player", {0.7684776f, 0.8789713f}},
    {"brawler", "Brawler", "character_brawler", {0.7684776f, 0.8789713f}},
    {"crazy", "Crazy", "character_crazy", {0.7684776f, 0.8789713f}},
    {"ranger", "Ranger", "character_ranger", {0.7784776f, 0.8789713f}},
    {"mage", "Mage", "character_mage", {0.8692388f, 0.9197325f}},
}};
struct MapDefinition { const char* id; const char* name; const char* floorImage; glm::vec4 background; glm::vec2 floorCenter; glm::vec2 floorSize; float floorAngle; bool floorFlipY; };
inline const std::array<MapDefinition, 5> Maps{{
    {"MapZEro", "MAP 1", "map_floor", {0.47058827f, 0.4039216f, 0.34509805f, 1.0f}, {10.8336087f, -1.32e-06f}, {22.0f, 17.5f}, 1.57079633f, true},
    {"MapOne", "MAP 2", "map_floor", {0.34509805f, 0.30588236f, 0.25882354f, 1.0f}, {10.8336087f, -1.32e-06f}, {22.0f, 17.5f}, 1.57079633f, true},
    {"MapTwo", "MAP 3", "map_floor", {0.47450984f, 0.3921569f, 0.3803922f, 1.0f}, {10.8336087f, -1.32e-06f}, {22.0f, 17.5f}, 1.57079633f, true},
    {"MapThree", "MAP 4", "map_floor", {0.3921569f, 0.3921569f, 0.3921569f, 1.0f}, {10.8336087f, -1.32e-06f}, {22.0f, 17.5f}, 1.57079633f, true},
    {"MapFour", "MAP 5", "map_floor", {0.3137255f, 0.3647059f, 0.36078432f, 1.0f}, {10.8336087f, -1.32e-06f}, {22.0f, 17.5f}, 1.57079633f, true},
}};
inline constexpr std::size_t RandomMap = 5;
inline const glm::vec2 MapFloorNativeSize{5.1194647f, 5.1193033f};
// Border order is left, bottom, right, top in the unrotated sprite.
inline const glm::vec4 MapFloorBorder{0.8097325f, 0.7095709f, 0.8997322f, 0.89973236f};
} // namespace Brotato
