#pragma once
// Generated by tools/import_brotato_enemy_art.py; do not edit.
#include <array>
#include <glm/glm.hpp>
namespace Brotato {
struct EnemyArt { glm::vec2 size, pivot; };
inline const std::array<EnemyArt, 8> ExtraEnemyArt{{
    {{0.899465f, 0.8884776f}, {0.4444114f, 0.5506484f}}, // enemy_fast
    {{0.8691791f, 0.9284776f}, {0.51685417f, 0.52692574f}}, // enemy_armored
    {{0.9096034f, 0.8789713f}, {0.5055729f, 0.54522693f}}, // enemy_ranged
    {{0.999465f, 1.1284776f}, {0.48999465f, 0.5044308f}}, // enemy_charger
    {{1.2494272f, 1.5084775f}, {0.5078222f, 0.533146f}}, // enemy_elite
    {{1.6789713f, 1.7784775f}, {0.47632295f, 0.62370133f}}, // enemy_boss
    {{0.9084776f, 0.9597325f}, {0.5055037f, 0.5209785f}}, // enemy_healer
    {{0.9489713f, 1.4389713f}, {0.50500876f, 0.48592967f}}, // enemy_summoner
}};
} // namespace Brotato
