#pragma once
// Generated by tools/import_brotato_build_art.py; do not edit.
#include <array>
#include <glm/glm.hpp>
namespace Brotato {
struct ItemArt { glm::vec2 size; };
inline const std::array<ItemArt,10> ItemArtCatalog{{
    {{0.6689713f,0.60897133f}}, // item_lens
    {{0.7484776f,0.8389713f}}, // item_coffee
    {{0.849465f,0.7584776f}}, // item_beanie
    {{0.7593034f,0.85910965f}}, // item_vest
    {{0.8893034f,0.7084776f}}, // item_plant
    {{0.8184776f,0.6489713f}}, // item_cake
    {{0.8789713f,0.8191913f}}, // item_bandana
    {{0.48897133f,0.8089713f}}, // item_bat
    {{0.7789713f,0.36847755f}}, // item_sunglasses
    {{0.9486751f,0.90887596f}}, // item_sausage
}};
} // namespace Brotato
