// Generated by tools/import_brotato_selection.py. Do not edit by hand.
#pragma once
#include "Brotato/Public/weapon_definitions.h"
#include <array>

namespace Brotato {
// The source enables exactly one starter weapon; these are choices, not slots.
struct WeaponSelectionDefinition { WeaponKind kind; const char* image; glm::vec2 size; };
inline constexpr std::array<WeaponSelectionDefinition, WeaponCount> WeaponSelections{{
    {WeaponKind::Wand, "select_wand", {0.8489713f, 0.8995858f}},
    {WeaponKind::Torch, "select_torch", {0.9497325f, 0.9497325f}},
    {WeaponKind::Laser, "select_laser", {0.8584776f, 0.6689713f}},
    {WeaponKind::Knife, "select_knife", {0.7687967f, 0.8089713f}},
    {WeaponKind::Gun, "select_gun", {0.8489713f, 0.8389713f}},
    {WeaponKind::Burst, "select_burst", {0.9392388f, 0.68910965f}},
}};
// Only diff_0 has a button binding; no source difficulty modifiers exist.
struct DifficultyDefinition { const char* id; const char* name; const char* image; glm::vec2 size; };
inline constexpr std::array<DifficultyDefinition, 1> Difficulties{{
    {"diff_0", "DIFFICULTY 0", "difficulty_0", {0.59897133f, 0.7489713f}},
}};
} // namespace Brotato
