#pragma once
// Generated by tools/import_brotato_weapon_geometry.py; do not edit.
#include <array>
#include <glm/glm.hpp>
namespace Brotato {
struct LocalSpriteGeometry { glm::vec2 offset{0}, axisX{1,0}, axisY{0,1}, size{1}, pivot{.5f}; };
struct WeaponGeometry { glm::vec2 scriptOffset, rootOffset; float idleAngle; bool idleReflected; LocalSpriteGeometry body; glm::vec2 firePoint; LocalSpriteGeometry projectile, muzzle; glm::vec2 muzzleParent, muzzleParentX, muzzleParentY; };
inline const std::array<WeaponGeometry, 6> SourceWeaponGeometry{{
    {{0.014f, -0.029f}, {0.014f, -0.029f}, 0.530580027f, false, {{0.22f, 0.f}, {0.999590379f, 0.0286194765f}, {-0.0286194765f, 0.999590379f}, {1.0887257f, 0.23880972f}, {0.51389146f, 0.5202418f}}, {0.692806249f, 0.0135370124f}, {{0.f, 0.f}, {1.f, 0.f}, {0.f, 1.f}, {0.47867508f, 0.48847755f}, {0.5002063f, 0.48976415f}}, {}, {0.f, 0.f}, {1.f, 0.f}, {0.f, 1.f}}, // Wand
    {{0.f, 0.f}, {0.f, 0.f}, 1.57079633f, true, {{0.22f, 0.05f}, {1.f, 0.f}, {0.f, 1.f}, {0.999465f, 0.28897127f}, {0.5f, 0.55105406f}}, {0.f, 0.f}, {}, {}, {0.f, 0.f}, {1.f, 0.f}, {0.f, 1.f}}, // Torch
    {{0.f, 0.f}, {0.f, 0.f}, 1.57079633f, true, {{0.22f, 0.05f}, {1.f, 0.f}, {0.f, 1.f}, {0.58880974f, 0.38897125f}, {0.61011016f, 0.79628634f}}, {0.f, 0.f}, {}, {}, {0.f, 0.f}, {1.f, 0.f}, {0.f, 1.f}}, // Laser
    {{0.f, 0.f}, {0.f, 0.f}, 1.57079633f, true, {{0.22f, 0.f}, {1.f, 0.f}, {0.f, 1.f}, {0.7089713f, 0.21919838f}, {0.5779254f, 0.547265f}}, {0.f, 0.f}, {}, {}, {0.f, 0.f}, {1.f, 0.f}, {0.f, 1.f}}, // Knife
    {{0.f, 0.f}, {0.f, 0.f}, 1.57079633f, true, {{0.22f, 0.f}, {1.f, 0.f}, {0.f, 1.f}, {0.6893034f, 0.46847755f}, {0.5361513f, 0.7668218f}}, {0.516f, -0.049f}, {{0.f, 0.f}, {1.f, 0.f}, {0.f, 1.f}, {1.02f, 0.4f}, {0.5f, 0.5f}}, {{0.094f, 0.025f}, {0.f, 1.f}, {1.f, 0.f}, {1.f, 0.96f}, {0.5f, 0.5f}}, {0.516f, -0.049f}, {1.f, 0.f}, {0.f, 1.f}}, // Gun
    {{0.f, 0.f}, {0.f, 0.f}, 1.57079633f, true, {{0.22f, 0.056f}, {1.f, 0.f}, {0.f, 1.f}, {0.909465f, 0.35880974f}, {0.47251132f, 0.7782364f}}, {0.628f, 0.053f}, {{0.f, 0.f}, {1.f, 0.f}, {0.f, 1.f}, {1.02f, 0.4f}, {0.5f, 0.5f}}, {{0.094f, 0.025f}, {0.f, 1.f}, {1.f, 0.f}, {1.f, 0.96f}, {0.5f, 0.5f}}, {0.628f, 0.053f}, {1.f, 0.f}, {0.f, 1.f}}, // Burst
}};
struct BeamSegmentGeometry { glm::vec2 center; LocalSpriteGeometry sprite; };
inline const std::array<BeamSegmentGeometry, 6> SourceBeamSegments{{
    {{0.687f, 0.f}, {{0.687f, 0.f}, {0.78787f, 0.f}, {0.f, 0.78787f}, {1.32f, 0.56f}, {0.5f, 0.5f}}},
    {{1.10200028f, 0.f}, {{1.10200028f, 0.f}, {0.78787f, 0.f}, {0.f, 0.78787f}, {1.32f, 0.56f}, {0.5f, 0.5f}}},
    {{1.48100018f, 0.f}, {{1.48100018f, 0.f}, {0.78787f, 0.f}, {0.f, 0.78787f}, {1.32f, 0.56f}, {0.5f, 0.5f}}},
    {{1.96100044f, 0.f}, {{1.96100044f, 0.f}, {0.78787f, 0.f}, {0.f, 0.78787f}, {1.32f, 0.56f}, {0.5f, 0.5f}}},
    {{2.50900048f, 0.f}, {{2.50900048f, 0.f}, {0.78787f, 0.f}, {0.f, 0.78787f}, {1.32f, 0.56f}, {0.5f, 0.5f}}},
    {{2.93300049f, 0.f}, {{2.93300049f, 0.f}, {0.78787f, 0.f}, {0.f, 0.78787f}, {1.32f, 0.56f}, {0.5f, 0.5f}}},
}};
inline const std::array<float, 6> LaserCenters{0.687f, 1.10200028f, 1.48100018f, 1.96100044f, 2.50900048f, 2.93300049f};
struct BurstPath { glm::vec2 start, end; float angle; };
inline const std::array<BurstPath, 4> BurstPaths{{
    {{0.317f, -0.135f}, {3.146f, -0.796f}, -0.403834281f},
    {{0.313f, 0.096f}, {3.076f, 0.555f}, 0.403826946f},
    {{0.228f, -0.328f}, {3.233f, -1.744f}, -0.654020911f},
    {{0.233f, 0.238f}, {3.148f, 1.519f}, 0.654027058f},
}};
} // namespace Brotato
