#pragma once

// =============================================
//  Auto generated by module_include_gen
//  Do not edit by hand.
//
//  设计目标：
//  1. 集中列出所有模块类型与固定槽位
//  2. 让 ModuleManager 可根据该表生成模块单例成员
//  3. 让外部/插件用相同头文件把类型参数映射到固定槽位
//  4. 跨 CRT / 跨 DLL 边界时只传 raw pointer + C ABI 风格函数
// =============================================

#include <cstddef>
#include <type_traits>

#include "application_module.h"
#include "render_module.h"

// 正序：用于构造 / 启动 / 建表
#define MODULE_INCLUDE_GEN_MODULES(X) \
    X(0, Application::ApplicationModule, applicationModule_); \
    X(1, Render::RenderModule,          renderModule_);

// 逆序：用于关闭 / 回滚
#define MODULE_INCLUDE_GEN_MODULES_REVERSE(X) \
    X(1, Render::RenderModule,          renderModule_); \
    X(0, Application::ApplicationModule, applicationModule_);

namespace ModuleIncludeGen {

inline constexpr std::size_t kModuleCount = 2;

template<typename T>
struct HasModuleSlot : std::false_type {};

template<typename T>
struct ModuleSlot;

template<typename T>
struct ModuleTypeName;

#define MODULE_INCLUDE_GEN_DECLARE_TRAITS(index, type, member)                \
    template<>                                                                \
    struct HasModuleSlot<type> : std::true_type {};                           \
                                                                              \
    template<>                                                                \
    struct ModuleSlot<type> {                                                 \
        static constexpr std::size_t kIndex = index;                          \
    };                                                                        \
                                                                              \
    template<>                                                                \
    struct ModuleTypeName<type> {                                             \
        static constexpr const char* Get() noexcept { return #type; }         \
    };

MODULE_INCLUDE_GEN_MODULES(MODULE_INCLUDE_GEN_DECLARE_TRAITS)
#undef MODULE_INCLUDE_GEN_DECLARE_TRAITS

} // namespace ModuleIncludeGen
