// Dynamic terrain demo for chickenyours/OpenglLearn.
// Generated by apply_dynamic_terrain.py.
// Uses the repository's ApplicationWindow + Render modules only.
// Terrain data stays in RAM; only nearby GPU meshes are streamed.

#include <algorithm>
#include <array>
#include <atomic>
#include <chrono>
#include <cmath>
#include <condition_variable>
#include <cstdint>
#include <deque>
#include <iostream>
#include <memory>
#include <mutex>
#include <sstream>
#include <thread>
#include <unordered_map>
#include <unordered_set>
#include <utility>
#include <vector>

#include <glfw/glfw3.h>

#include <glm/glm.hpp>
#include <glm/gtc/matrix_transform.hpp>

#include "ApplicationWindow/module.h"
#include "Render/module.h"
#include "Render/Systems/callback_system.h"
#include "Render/Public/RHIResourceType/Buffer/uniform_buffer.h"
#include "Render/Public/RHIResourceType/Pipeline/pipeline.h"
#include "Render/Public/RHIResourceType/Shader/shader.h"
#include "Render/Public/RHIResourceType/Shader/shader_source.h"

namespace {

constexpr int kChunkSize = 16;
constexpr int kLoadRadius = 6;      // 13 x 13 candidate chunks around camera.
constexpr int kKeepRadius = 8;      // GPU mesh hysteresis.
constexpr int kMaxUploadsPerFrame = 8;
constexpr std::size_t kMaxQueuedGeneration = 128;

const glm::vec4 kSkyColor{0.44f, 0.68f, 0.90f, 1.0f};

struct Vertex {
    glm::vec3 position{0.0f};
    glm::vec3 normal{0.0f, 1.0f, 0.0f};
    glm::vec3 color{1.0f};
};

struct CpuMesh {
    std::vector<Vertex> vertices;
    std::vector<std::uint32_t> indices;
};

struct ChunkData {
    std::array<std::uint8_t, kChunkSize * kChunkSize> heights{};
    CpuMesh mesh;
};

struct ChunkCoord {
    int x = 0;
    int z = 0;

    bool operator==(const ChunkCoord& other) const noexcept {
        return x == other.x && z == other.z;
    }
};

struct ChunkCoordHash {
    std::size_t operator()(const ChunkCoord& c) const noexcept {
        std::uint64_t x = static_cast<std::uint32_t>(c.x);
        std::uint64_t z = static_cast<std::uint32_t>(c.z);
        std::uint64_t h = (x << 32u) ^ z;
        h ^= h >> 33u;
        h *= 0xff51afd7ed558ccdULL;
        h ^= h >> 33u;
        h *= 0xc4ceb9fe1a85ec53ULL;
        h ^= h >> 33u;
        return static_cast<std::size_t>(h);
    }
};

int ChebyshevDistance(ChunkCoord a, ChunkCoord b) {
    return std::max(std::abs(a.x - b.x), std::abs(a.z - b.z));
}

ChunkCoord WorldToChunk(const glm::vec3& world) {
    return {
        static_cast<int>(std::floor(world.x / static_cast<float>(kChunkSize))),
        static_cast<int>(std::floor(world.z / static_cast<float>(kChunkSize)))
    };
}

Render::VertexLayout TerrainVertexLayout() {
    Render::VertexLayout layout;
    layout.typeSlots = {
        Render::VertexFieldType::Vec3,
        Render::VertexFieldType::Vec3,
        Render::VertexFieldType::Vec3
    };
    return layout;
}

struct alignas(16) ViewConstants {
    glm::mat4 viewProjection{1.0f};
    glm::vec4 cameraPosition{0.0f, 0.0f, 0.0f, 1.0f};
};

struct alignas(16) ObjectConstants {
    glm::mat4 model{1.0f};
};

constexpr char kVertexShader[] = R"GLSL(
#version 450 core

layout(location = 0) in vec3 aPosition;
layout(location = 1) in vec3 aNormal;
layout(location = 2) in vec3 aColor;

layout(std140, binding = 0) uniform ViewData {
    mat4 uViewProjection;
    vec4 uCameraPosition;
};

layout(std140, binding = 1) uniform ObjectData {
    mat4 uModel;
};

out vec3 vWorldPosition;
out vec3 vNormal;
out vec3 vColor;

void main() {
    vec4 world = uModel * vec4(aPosition, 1.0);
    vWorldPosition = world.xyz;
    vNormal = normalize(mat3(uModel) * aNormal);
    vColor = aColor;
    gl_Position = uViewProjection * world;
}
)GLSL";

constexpr char kFragmentShader[] = R"GLSL(
#version 450 core

layout(std140, binding = 0) uniform ViewData {
    mat4 uViewProjection;
    vec4 uCameraPosition;
};

in vec3 vWorldPosition;
in vec3 vNormal;
in vec3 vColor;

layout(location = 0) out vec4 FragColor;

void main() {
    const vec3 sky = vec3(0.44, 0.68, 0.90);
    vec3 n = normalize(vNormal);
    vec3 lightDirection = normalize(vec3(0.42, 0.86, 0.28));
    float light = 0.34 + 0.66 * max(dot(n, lightDirection), 0.0);

    vec3 color = vColor * light;

    // The fog finishes before the GPU keep/load boundary becomes visible.
    float d = distance(vWorldPosition, uCameraPosition.xyz);
    float fog = smoothstep(62.0, 88.0, d);
    color = mix(color, sky, fog);

    FragColor = vec4(color, 1.0);
}
)GLSL";

class GpuProgram {
public:
    explicit GpuProgram(Render::RHIDevice* device)
        : device_(device) {}

    void Start() {
        Render::CreateUniformBufferDesc view{};
        view.byteSize = static_cast<std::uint32_t>(sizeof(ViewConstants));
        view.usage = Render::BufferUsage::Dynamic;
        device_->async_CreateUniformBuffer(
            view,
            [this](Render::RenderResourceHandle<Render::UniformBufferSpec> handle) {
                viewUniform_ = handle;
                if (!handle.IsValid()) failed_ = true;
            });

        Render::CreateUniformBufferDesc object{};
        object.byteSize = static_cast<std::uint32_t>(sizeof(ObjectConstants));
        object.usage = Render::BufferUsage::Dynamic;
        device_->async_CreateUniformBuffer(
            object,
            [this](Render::RenderResourceHandle<Render::UniformBufferSpec> handle) {
                objectUniform_ = handle;
                if (!handle.IsValid()) failed_ = true;
            });

        Render::CreateShaderSourceDesc vs{};
        vs.type = Render::ShaderSourceType::Vertex;
        vs.codeSource = kVertexShader;
        vs.size = sizeof(kVertexShader) - 1;
        device_->async_CreateShaderSource(
            vs,
            [this](Render::RenderResourceHandle<Render::ShaderSourceSpec> handle) {
                vertexShader_ = handle;
                if (!handle.IsValid()) {
                    failed_ = true;
                    return;
                }
                TryCreateProgram();
            });

        Render::CreateShaderSourceDesc fs{};
        fs.type = Render::ShaderSourceType::Fragment;
        fs.codeSource = kFragmentShader;
        fs.size = sizeof(kFragmentShader) - 1;
        device_->async_CreateShaderSource(
            fs,
            [this](Render::RenderResourceHandle<Render::ShaderSourceSpec> handle) {
                fragmentShader_ = handle;
                if (!handle.IsValid()) {
                    failed_ = true;
                    return;
                }
                TryCreateProgram();
            });
    }

    bool Ready() const {
        return pipeline_.IsValid()
            && viewUniform_.IsValid()
            && objectUniform_.IsValid();
    }

    bool Failed() const {
        return failed_;
    }

    Render::RenderResourceHandle<Render::PipelineSpec> Pipeline() const {
        return pipeline_;
    }

    Render::RenderResourceHandle<Render::UniformBufferSpec> ViewUniform() const {
        return viewUniform_;
    }

    Render::RenderResourceHandle<Render::UniformBufferSpec> ObjectUniform() const {
        return objectUniform_;
    }

    void Shutdown() {
        if (pipeline_.IsValid()) {
            device_->async_DeletePipeline(pipeline_);
            pipeline_ = {};
        }
        if (viewUniform_.IsValid()) {
            device_->async_DeleteUniformBuffer(viewUniform_);
            viewUniform_ = {};
        }
        if (objectUniform_.IsValid()) {
            device_->async_DeleteUniformBuffer(objectUniform_);
            objectUniform_ = {};
        }
    }

private:
    void TryCreateProgram() {
        if (programRequested_
            || !vertexShader_.IsValid()
            || !fragmentShader_.IsValid()) {
            return;
        }

        programRequested_ = true;

        Render::CreateGraphicShaderDesc shader{};
        shader.vertexShaderSource = vertexShader_;
        shader.fragmentShaderSource = fragmentShader_;

        device_->async_CreateGraphicShader(
            shader,
            [this](Render::RenderResourceHandle<Render::ShaderProgramSpec> handle) {
                shaderProgram_ = handle;
                if (!handle.IsValid()) {
                    failed_ = true;
                    return;
                }

                Render::CreatePipelineDesc desc{};
                desc.spec.shaderProgram = shaderProgram_;
                desc.spec.topology = Render::PrimitiveTopology::TriangleList;
                desc.spec.expectVertexLayout = TerrainVertexLayout();
                desc.spec.cullMode = Render::CullMode::None;
                desc.spec.depthTest = true;
                desc.spec.depthWrite = true;
                desc.spec.depthCompare = Render::CompareOp::LessEqual;

                device_->async_CreatePipeline(
                    desc,
                    [this](Render::RenderResourceHandle<Render::PipelineSpec> created) {
                        pipeline_ = created;
                        if (!created.IsValid()) failed_ = true;
                    });
            });
    }

    Render::RHIDevice* device_ = nullptr;
    Render::RenderResourceHandle<Render::ShaderSourceSpec> vertexShader_{};
    Render::RenderResourceHandle<Render::ShaderSourceSpec> fragmentShader_{};
    Render::RenderResourceHandle<Render::ShaderProgramSpec> shaderProgram_{};
    Render::RenderResourceHandle<Render::PipelineSpec> pipeline_{};
    Render::RenderResourceHandle<Render::UniformBufferSpec> viewUniform_{};
    Render::RenderResourceHandle<Render::UniformBufferSpec> objectUniform_{};
    bool programRequested_ = false;
    bool failed_ = false;
};

class FlyCamera {
public:
    glm::vec3 position{8.0f, 21.0f, 28.0f};
    float yaw = -90.0f;
    float pitch = -29.0f;

    void Start(GLFWwindow* window) {
        glfwSetInputMode(window, GLFW_CURSOR, GLFW_CURSOR_DISABLED);
        firstMouse_ = true;
    }

    void Update(GLFWwindow* window, float dt) {
        if (glfwGetKey(window, GLFW_KEY_ESCAPE) == GLFW_PRESS) {
            glfwSetWindowShouldClose(window, GLFW_TRUE);
        }

        double x = 0.0;
        double y = 0.0;
        glfwGetCursorPos(window, &x, &y);

        if (firstMouse_) {
            lastX_ = x;
            lastY_ = y;
            firstMouse_ = false;
        }

        constexpr float sensitivity = 0.10f;
        yaw += static_cast<float>(x - lastX_) * sensitivity;
        pitch -= static_cast<float>(y - lastY_) * sensitivity;
        pitch = std::clamp(pitch, -89.0f, 89.0f);
        lastX_ = x;
        lastY_ = y;

        glm::vec3 horizontal = Forward();
        horizontal.y = 0.0f;
        if (glm::dot(horizontal, horizontal) < 0.0001f) {
            horizontal = glm::vec3(0.0f, 0.0f, -1.0f);
        } else {
            horizontal = glm::normalize(horizontal);
        }

        const glm::vec3 right = glm::normalize(
            glm::cross(horizontal, glm::vec3(0.0f, 1.0f, 0.0f)));

        float speed = 12.0f;
        if (glfwGetKey(window, GLFW_KEY_LEFT_SHIFT) == GLFW_PRESS) {
            speed = 34.0f;
        }
        speed *= dt;

        if (glfwGetKey(window, GLFW_KEY_W) == GLFW_PRESS) position += horizontal * speed;
        if (glfwGetKey(window, GLFW_KEY_S) == GLFW_PRESS) position -= horizontal * speed;
        if (glfwGetKey(window, GLFW_KEY_A) == GLFW_PRESS) position -= right * speed;
        if (glfwGetKey(window, GLFW_KEY_D) == GLFW_PRESS) position += right * speed;
        if (glfwGetKey(window, GLFW_KEY_SPACE) == GLFW_PRESS) position.y += speed;
        if (glfwGetKey(window, GLFW_KEY_LEFT_CONTROL) == GLFW_PRESS) position.y -= speed;
    }

    glm::vec3 Forward() const {
        const float y = glm::radians(yaw);
        const float p = glm::radians(pitch);
        return glm::normalize(glm::vec3(
            std::cos(y) * std::cos(p),
            std::sin(p),
            std::sin(y) * std::cos(p)));
    }

    glm::mat4 View() const {
        return glm::lookAt(
            position,
            position + Forward(),
            glm::vec3(0.0f, 1.0f, 0.0f));
    }

private:
    bool firstMouse_ = true;
    double lastX_ = 0.0;
    double lastY_ = 0.0;
};

std::uint32_t Hash2(int x, int z, std::uint32_t seed) {
    std::uint32_t h = static_cast<std::uint32_t>(x) * 0x8da6b343u;
    h ^= static_cast<std::uint32_t>(z) * 0xd8163841u;
    h ^= seed * 0xcb1ab31fu;
    h ^= h >> 16u;
    h *= 0x7feb352du;
    h ^= h >> 15u;
    h *= 0x846ca68bu;
    h ^= h >> 16u;
    return h;
}

float Hash01(int x, int z, std::uint32_t seed) {
    return static_cast<float>(Hash2(x, z, seed) & 0x00ffffffu)
        / static_cast<float>(0x01000000u);
}

float Fade(float t) {
    return t * t * (3.0f - 2.0f * t);
}

float ValueNoise(float x, float z, float grid, std::uint32_t seed) {
    const float gx = x / grid;
    const float gz = z / grid;

    const int x0 = static_cast<int>(std::floor(gx));
    const int z0 = static_cast<int>(std::floor(gz));
    const int x1 = x0 + 1;
    const int z1 = z0 + 1;

    const float tx = Fade(gx - static_cast<float>(x0));
    const float tz = Fade(gz - static_cast<float>(z0));

    const float a = Hash01(x0, z0, seed);
    const float b = Hash01(x1, z0, seed);
    const float c = Hash01(x0, z1, seed);
    const float d = Hash01(x1, z1, seed);

    const float ab = a + (b - a) * tx;
    const float cd = c + (d - c) * tx;
    return ab + (cd - ab) * tz;
}

int WorldHeight(int worldX, int worldZ) {
    const float large = ValueNoise(
        static_cast<float>(worldX),
        static_cast<float>(worldZ),
        31.0f,
        0x13572468u);
    const float medium = ValueNoise(
        static_cast<float>(worldX),
        static_cast<float>(worldZ),
        12.0f,
        0x24681357u);
    const float small = ValueNoise(
        static_cast<float>(worldX),
        static_cast<float>(worldZ),
        5.0f,
        0x00c0ffeeu);

    const float h = 4.0f + large * 8.0f + medium * 3.5f + small * 1.5f;
    return std::clamp(static_cast<int>(std::floor(h)), 2, 19);
}

glm::vec3 SurfaceColor(int y, int topY, glm::ivec3 normal) {
    if (normal.y > 0) {
        const float variation = 0.93f + 0.04f * static_cast<float>((topY * 17) % 3);
        return glm::vec3(0.25f, 0.63f, 0.20f) * variation;
    }

    if (y >= topY - 3) {
        return glm::vec3(0.45f, 0.31f, 0.18f);
    }

    return glm::vec3(0.42f, 0.45f, 0.49f);
}

void EmitQuad(
    CpuMesh& mesh,
    const std::array<glm::vec3, 4>& positions,
    glm::vec3 normal,
    glm::vec3 color) {
    const std::uint32_t first =
        static_cast<std::uint32_t>(mesh.vertices.size());

    for (const glm::vec3& p : positions) {
        mesh.vertices.push_back(Vertex{p, normal, color});
    }

    mesh.indices.push_back(first + 0);
    mesh.indices.push_back(first + 1);
    mesh.indices.push_back(first + 2);
    mesh.indices.push_back(first + 0);
    mesh.indices.push_back(first + 2);
    mesh.indices.push_back(first + 3);
}

std::shared_ptr<ChunkData> GenerateChunk(ChunkCoord coord) {
    auto result = std::make_shared<ChunkData>();

    const int baseX = coord.x * kChunkSize;
    const int baseZ = coord.z * kChunkSize;

    for (int z = 0; z < kChunkSize; ++z) {
        for (int x = 0; x < kChunkSize; ++x) {
            const int h = WorldHeight(baseX + x, baseZ + z);
            result->heights[
                static_cast<std::size_t>(z * kChunkSize + x)] =
                static_cast<std::uint8_t>(h);
        }
    }

    CpuMesh& mesh = result->mesh;
    mesh.vertices.reserve(kChunkSize * kChunkSize * 8);
    mesh.indices.reserve(kChunkSize * kChunkSize * 12);

    for (int z = 0; z < kChunkSize; ++z) {
        for (int x = 0; x < kChunkSize; ++x) {
            const int worldX = baseX + x;
            const int worldZ = baseZ + z;
            const int h = WorldHeight(worldX, worldZ);
            const float xf = static_cast<float>(x);
            const float zf = static_cast<float>(z);
            const float top = static_cast<float>(h);

            EmitQuad(
                mesh,
                {
                    glm::vec3{xf,       top, zf},
                    glm::vec3{xf,       top, zf + 1.0f},
                    glm::vec3{xf + 1.0f,top, zf + 1.0f},
                    glm::vec3{xf + 1.0f,top, zf}
                },
                glm::vec3{0.0f, 1.0f, 0.0f},
                SurfaceColor(h - 1, h, glm::ivec3{0, 1, 0}));

            const int west = WorldHeight(worldX - 1, worldZ);
            if (west < h) {
                const float bottom = static_cast<float>(west);
                EmitQuad(
                    mesh,
                    {
                        glm::vec3{xf, bottom, zf + 1.0f},
                        glm::vec3{xf, bottom, zf},
                        glm::vec3{xf, top,    zf},
                        glm::vec3{xf, top,    zf + 1.0f}
                    },
                    glm::vec3{-1.0f, 0.0f, 0.0f},
                    SurfaceColor(west, h, glm::ivec3{-1, 0, 0}));
            }

            const int east = WorldHeight(worldX + 1, worldZ);
            if (east < h) {
                const float bottom = static_cast<float>(east);
                EmitQuad(
                    mesh,
                    {
                        glm::vec3{xf + 1.0f, bottom, zf},
                        glm::vec3{xf + 1.0f, bottom, zf + 1.0f},
                        glm::vec3{xf + 1.0f, top,    zf + 1.0f},
                        glm::vec3{xf + 1.0f, top,    zf}
                    },
                    glm::vec3{1.0f, 0.0f, 0.0f},
                    SurfaceColor(east, h, glm::ivec3{1, 0, 0}));
            }

            const int north = WorldHeight(worldX, worldZ - 1);
            if (north < h) {
                const float bottom = static_cast<float>(north);
                EmitQuad(
                    mesh,
                    {
                        glm::vec3{xf + 1.0f, bottom, zf},
                        glm::vec3{xf,        bottom, zf},
                        glm::vec3{xf,        top,    zf},
                        glm::vec3{xf + 1.0f, top,    zf}
                    },
                    glm::vec3{0.0f, 0.0f, -1.0f},
                    SurfaceColor(north, h, glm::ivec3{0, 0, -1}));
            }

            const int south = WorldHeight(worldX, worldZ + 1);
            if (south < h) {
                const float bottom = static_cast<float>(south);
                EmitQuad(
                    mesh,
                    {
                        glm::vec3{xf,        bottom, zf + 1.0f},
                        glm::vec3{xf + 1.0f, bottom, zf + 1.0f},
                        glm::vec3{xf + 1.0f, top,    zf + 1.0f},
                        glm::vec3{xf,        top,    zf + 1.0f}
                    },
                    glm::vec3{0.0f, 0.0f, 1.0f},
                    SurfaceColor(south, h, glm::ivec3{0, 0, 1}));
            }
        }
    }

    return result;
}

struct GpuTicket {
    Render::RenderResourceHandle<Render::VertexBufferSpec> handle{};
    std::uint32_t indexCount = 0;
    bool pending = true;
    bool retired = false;
};

struct CompletedChunk {
    ChunkCoord coord;
    std::shared_ptr<ChunkData> data;
};

class ChunkStreamer {
public:
    explicit ChunkStreamer(Render::RHIDevice* device)
        : device_(device) {
        unsigned count = std::thread::hardware_concurrency();
        if (count == 0) count = 2;
        count = std::min(2u, count);

        for (unsigned i = 0; i < count; ++i) {
            workers_.emplace_back([this]() {
                WorkerLoop();
            });
        }
    }

    ~ChunkStreamer() {
        {
            std::lock_guard<std::mutex> lock(workMutex_);
            stopping_ = true;
        }
        workCv_.notify_all();

        for (std::thread& worker : workers_) {
            if (worker.joinable()) worker.join();
        }

        for (auto& pair : active_) {
            RetireTicket(pair.second);
        }
        active_.clear();
    }

    void Update(const glm::vec3& cameraPosition) {
        const ChunkCoord center = WorldToChunk(cameraPosition);

        DrainGenerated();
        RetireFar(center);

        std::vector<ChunkCoord> wanted;
        wanted.reserve(
            static_cast<std::size_t>(
                (kLoadRadius * 2 + 1) * (kLoadRadius * 2 + 1)));

        for (int dz = -kLoadRadius; dz <= kLoadRadius; ++dz) {
            for (int dx = -kLoadRadius; dx <= kLoadRadius; ++dx) {
                wanted.push_back({center.x + dx, center.z + dz});
            }
        }

        std::sort(
            wanted.begin(),
            wanted.end(),
            [center](const ChunkCoord& a, const ChunkCoord& b) {
                const int ax = a.x - center.x;
                const int az = a.z - center.z;
                const int bx = b.x - center.x;
                const int bz = b.z - center.z;
                return ax * ax + az * az < bx * bx + bz * bz;
            });

        int uploads = 0;
        for (ChunkCoord coord : wanted) {
            if (active_.find(coord) != active_.end()) continue;

            const auto cached = cache_.find(coord);
            if (cached != cache_.end()) {
                if (uploads < kMaxUploadsPerFrame) {
                    BeginUpload(coord, cached->second);
                    ++uploads;
                }
                continue;
            }

            if (queued_.find(coord) == queued_.end()
                && queued_.size() < kMaxQueuedGeneration) {
                queued_.insert(coord);
                {
                    std::lock_guard<std::mutex> lock(workMutex_);
                    workQueue_.push_back(coord);
                }
                workCv_.notify_one();
            }
        }
    }

    void Record(
        Render::RHIFrameEncoder& frame,
        Render::RenderResourceHandle<Render::UniformBufferSpec> objectUniform) const {
        for (const auto& pair : active_) {
            const ChunkCoord coord = pair.first;
            const std::shared_ptr<GpuTicket>& ticket = pair.second;

            if (!ticket
                || ticket->pending
                || ticket->retired
                || !ticket->handle.IsValid()
                || ticket->indexCount == 0) {
                continue;
            }

            ObjectConstants object{};
            object.model = glm::translate(
                glm::mat4(1.0f),
                glm::vec3(
                    static_cast<float>(coord.x * kChunkSize),
                    0.0f,
                    static_cast<float>(coord.z * kChunkSize)));

            if (!frame.UpdateUniformBuffer(objectUniform, object)) return;
            if (!frame.BindUniformBuffer(objectUniform, 1)) return;
            if (!frame.BindMesh(ticket->handle)) return;

            Render::RHICommand::DrawIndexed draw{};
            draw.indexCount = ticket->indexCount;
            if (!frame.DrawIndexed(draw)) return;
        }
    }

    std::size_t CacheCount() const {
        return cache_.size();
    }

    std::size_t ActiveCount() const {
        return active_.size();
    }

    std::size_t QueueCount() const {
        return queued_.size();
    }

    std::size_t ReadyCount() const {
        std::size_t count = 0;
        for (const auto& pair : active_) {
            const auto& ticket = pair.second;
            if (ticket
                && !ticket->pending
                && !ticket->retired
                && ticket->handle.IsValid()) {
                ++count;
            }
        }
        return count;
    }

private:
    void WorkerLoop() {
        for (;;) {
            ChunkCoord coord{};
            {
                std::unique_lock<std::mutex> lock(workMutex_);
                workCv_.wait(
                    lock,
                    [this]() {
                        return stopping_ || !workQueue_.empty();
                    });

                if (stopping_ && workQueue_.empty()) {
                    return;
                }

                coord = workQueue_.front();
                workQueue_.pop_front();
            }

            CompletedChunk result{};
            result.coord = coord;
            result.data = GenerateChunk(coord);

            {
                std::lock_guard<std::mutex> lock(completedMutex_);
                completed_.push_back(std::move(result));
            }
        }
    }

    void DrainGenerated() {
        std::deque<CompletedChunk> local;
        {
            std::lock_guard<std::mutex> lock(completedMutex_);
            local.swap(completed_);
        }

        for (CompletedChunk& completed : local) {
            queued_.erase(completed.coord);
            cache_.try_emplace(
                completed.coord,
                std::move(completed.data));
        }
    }

    void RetireTicket(const std::shared_ptr<GpuTicket>& ticket) {
        if (!ticket || ticket->retired) return;
        ticket->retired = true;

        if (ticket->handle.IsValid()) {
            device_->async_DeleteVertexBuffer(ticket->handle);
            ticket->handle = {};
        }
    }

    void RetireFar(ChunkCoord center) {
        for (auto it = active_.begin(); it != active_.end();) {
            if (ChebyshevDistance(it->first, center) <= kKeepRadius) {
                ++it;
                continue;
            }

            RetireTicket(it->second);
            it = active_.erase(it);
        }
    }

    void BeginUpload(
        ChunkCoord coord,
        const std::shared_ptr<ChunkData>& data) {
        if (!data || data->mesh.indices.empty()) return;

        auto ticket = std::make_shared<GpuTicket>();
        ticket->indexCount =
            static_cast<std::uint32_t>(data->mesh.indices.size());
        active_[coord] = ticket;

        Render::CreateMeshBufferDesc desc{};
        desc.vertexLayout = TerrainVertexLayout();
        desc.vertexCount =
            static_cast<std::uint32_t>(data->mesh.vertices.size());
        desc.vertexData = data->mesh.vertices.data();
        desc.vertexByteSize =
            data->mesh.vertices.size() * sizeof(Vertex);
        desc.indexCount =
            static_cast<std::uint32_t>(data->mesh.indices.size());
        desc.indexData = data->mesh.indices.data();
        desc.indexByteSize =
            data->mesh.indices.size() * sizeof(std::uint32_t);
        desc.indexType = Render::IndexType::UInt32;
        desc.usage = Render::BufferUsage::Static;

        Render::RHIDevice* device = device_;
        device_->async_CreateMeshBuffer(
            desc,
            [ticket, device](
                Render::RenderResourceHandle<Render::VertexBufferSpec> handle) {
                ticket->pending = false;

                if (ticket->retired) {
                    if (handle.IsValid()) {
                        device->async_DeleteVertexBuffer(handle);
                    }
                    return;
                }

                if (!handle.IsValid()) {
                    return;
                }

                ticket->handle = handle;
            });
    }

    Render::RHIDevice* device_ = nullptr;

    // Permanent in-memory terrain data cache.
    std::unordered_map<
        ChunkCoord,
        std::shared_ptr<ChunkData>,
        ChunkCoordHash> cache_;

    // Only nearby chunks have GPU tickets/resources.
    std::unordered_map<
        ChunkCoord,
        std::shared_ptr<GpuTicket>,
        ChunkCoordHash> active_;

    // Main-thread request set.
    std::unordered_set<ChunkCoord, ChunkCoordHash> queued_;

    std::mutex workMutex_;
    std::condition_variable workCv_;
    std::deque<ChunkCoord> workQueue_;
    bool stopping_ = false;
    std::vector<std::thread> workers_;

    std::mutex completedMutex_;
    std::deque<CompletedChunk> completed_;
};

void UpdateTitle(
    GLFWwindow* window,
    const FlyCamera& camera,
    const ChunkStreamer& streamer) {
    static double previous = -1.0;
    const double now = glfwGetTime();
    if (previous >= 0.0 && now - previous < 0.25) return;
    previous = now;

    const ChunkCoord center = WorldToChunk(camera.position);

    std::ostringstream title;
    title
        << "Dynamic Terrain | chunk "
        << center.x << "," << center.z
        << " | GPU " << streamer.ReadyCount()
        << "/" << streamer.ActiveCount()
        << " | RAM " << streamer.CacheCount()
        << " | queued " << streamer.QueueCount()
        << " | WASD + mouse, Shift fast";

    glfwSetWindowTitle(window, title.str().c_str());
}

} // namespace

int main() {
    ApplicationWindow::ApplicationWindowModule windowModule;
    Render::RenderModule renderModule;
    Render::System::CallBackSystem callbackSystem;

    if (!windowModule.Startup()) {
        std::cerr << "ApplicationWindow startup failed.\n";
        return 1;
    }

    if (!renderModule.Startup()) {
        std::cerr << "Render startup failed.\n";
        windowModule.Shutdown();
        return 2;
    }

    callbackSystem.OnStart();

    auto windowWeak =
        ApplicationWindow::ApplicationWindowModule::GetCurrentWindow();
    auto deviceWeak =
        Render::RenderModule::GetRHIDevice();

    ApplicationWindow::Window* window = windowWeak.Get();
    Render::RHIDevice* device = deviceWeak.Get();

    if (window == nullptr || device == nullptr) {
        std::cerr << "Window or RHIDevice unavailable.\n";
        callbackSystem.OnEnd();
        renderModule.Shutdown();
        windowModule.Shutdown();
        return 3;
    }

    GLFWwindow* nativeWindow = window->GetNativeWindow();

    FlyCamera camera;
    camera.Start(nativeWindow);

    GpuProgram gpu(device);
    gpu.Start();

    while (!window->ShouldClose() && !gpu.Ready() && !gpu.Failed()) {
        window->PollEvents();
        callbackSystem.OnTick();
        std::this_thread::sleep_for(std::chrono::milliseconds(1));
    }

    if (!gpu.Ready()) {
        std::cerr << "Failed to initialize terrain GPU resources.\n";
        gpu.Shutdown();
        callbackSystem.OnEnd();
        renderModule.Shutdown();
        windowModule.Shutdown();
        return 4;
    }

    {
        ChunkStreamer streamer(device);

        std::uint64_t frameIndex = 1;
        double previousTime = glfwGetTime();

        while (!window->ShouldClose()) {
            window->PollEvents();
            callbackSystem.OnTick();

            const double now = glfwGetTime();
            const float deltaSeconds = std::clamp(
                static_cast<float>(now - previousTime),
                0.0f,
                0.05f);
            previousTime = now;

            camera.Update(nativeWindow, deltaSeconds);
            streamer.Update(camera.position);
            UpdateTitle(nativeWindow, camera, streamer);

            int width = 0;
            int height = 0;
            glfwGetFramebufferSize(nativeWindow, &width, &height);

            if (width <= 0 || height <= 0) {
                std::this_thread::sleep_for(std::chrono::milliseconds(8));
                continue;
            }

            Render::RHICommand::BeginFrame begin{};
            begin.frameIndex = frameIndex++;
            begin.framebufferWidth = static_cast<std::uint32_t>(width);
            begin.framebufferHeight = static_cast<std::uint32_t>(height);
            begin.clearColor = kSkyColor;

            auto frame = device->BeginFrame(begin);

            Render::RHICommand::SetViewport viewport{};
            viewport.width = static_cast<std::uint32_t>(width);
            viewport.height = static_cast<std::uint32_t>(height);
            frame.SetViewport(viewport);

            const float aspect =
                static_cast<float>(width) / static_cast<float>(height);

            const glm::mat4 projection = glm::perspective(
                glm::radians(67.0f),
                aspect,
                0.1f,
                105.0f);

            ViewConstants view{};
            view.viewProjection = projection * camera.View();
            view.cameraPosition = glm::vec4(camera.position, 1.0f);

            if (!frame.UpdateUniformBuffer(gpu.ViewUniform(), view)
                || !frame.BindUniformBuffer(gpu.ViewUniform(), 0)
                || !frame.BindPipeline(gpu.Pipeline())) {
                std::cerr << "Failed to record frame setup.\n";
                break;
            }

            streamer.Record(frame, gpu.ObjectUniform());

            if (!frame.End(true)) {
                std::cerr << "Failed to end frame.\n";
                break;
            }

            if (!device->async_SubmitFrameCommands(
                    frame.GetCommandBuffer())) {
                std::cerr << "Failed to submit frame.\n";
                break;
            }

            std::this_thread::sleep_for(std::chrono::milliseconds(1));
        }

        callbackSystem.OnTick();
    }

    gpu.Shutdown();
    callbackSystem.OnTick();
    callbackSystem.OnEnd();

    renderModule.Shutdown();
    windowModule.Shutdown();
    return 0;
}
