#!/usr/bin/env python3
"""Import original item art for newly designed build/shop rules; source stays read-only."""
import argparse
import json
import math
from pathlib import Path
from PIL import Image
from import_brotato_assets import read_guid, sha256, sprite_data

def import_art(source, output, catalog_output):
    source=source.resolve(strict=True)
    output,catalog_output=output.resolve(),catalog_output.resolve()
    for destination in (output,catalog_output):
        if destination==source or source in destination.parents:
            raise ValueError('Output must be outside the read-only Unity source project')
    assets=source/'Assets'
    textures={read_guid(p):p.with_suffix('') for p in sorted((assets/'Texture2D').glob('*.png.meta'))}
    records,crops=[],[]
    for name,original in [('item_lens','lens'),('item_coffee','coffee'),('item_beanie','beanie'),
                          ('item_vest','leather_vest'),('item_plant','plant'),('item_cake','cake'),
                          ('item_bandana','bandana'),('item_bat','bat'),('item_sunglasses','sunglasses'),
                          ('item_sausage','scared_sausage')]:
        sprite=assets/'Sprite'/(original+'_icon.asset'); data=sprite_data(sprite); texture=textures[data['texture_guid']]
        with Image.open(texture) as image:
            image=image.convert('RGBA'); x,y,w,h=data['unity_rect_xywh']
            box=(math.floor(x),image.height-math.ceil(y+h),math.ceil(x+w),image.height-math.floor(y))
            if not (0<=box[0]<box[2]<=image.width and 0<=box[1]<box[3]<=image.height):
                raise ValueError('Sprite rectangle is outside its texture')
            crop=image.crop(box)
            if not crop.getchannel('A').getbbox(): raise ValueError('Transparent item Sprite')
        records.append(dict(image=name,source_sprite=sprite.relative_to(source).as_posix(),
            source_texture=texture.relative_to(source).as_posix(),sprite_guid=read_guid(sprite.with_suffix('.asset.meta')),
            inputs=[dict(path=p.relative_to(source).as_posix(),sha256=sha256(p)) for p in
                    (sprite,sprite.with_suffix('.asset.meta'),texture,texture.with_suffix('.png.meta'))],
            **data,size=[w/data['pixels_per_unit'],h/data['pixels_per_unit']],crop_top_left_ltrb=list(box),output=name+'.png'))
        crops.append(crop)
    output.mkdir(parents=True,exist_ok=True); catalog_output.mkdir(parents=True,exist_ok=True)
    for record,crop in zip(records,crops):
        crop.save(output/record['output'],format='PNG',optimize=False)
        record['output_sha256']=sha256(output/record['output'])
    manifest=dict(format_version=1,scope='Original item art; rewards, passive effects and shop economy are newly designed, not recovered source behavior.',assets=records)
    (output/'build_content_manifest.json').write_text(json.dumps(manifest,ensure_ascii=False,indent=2)+'\n',encoding='utf-8',newline='\n')
    def number(value):
        result=format(value,'.9g'); return result+('f' if '.' in result or 'e' in result else '.f')
    header=['#pragma once','// Generated by tools/import_brotato_build_art.py; do not edit.','#include <array>','#include <glm/glm.hpp>',
            'namespace Brotato {','struct ItemArt { glm::vec2 size; };',f'inline const std::array<ItemArt,{len(records)}> ItemArtCatalog{{{{']
    header+=['    {{'+','.join(number(v) for v in r['size'])+'}}, // '+r['image'] for r in records]
    header+=['}};','} // namespace Brotato','']
    (catalog_output/'item_art_catalog.h').write_text('\n'.join(header),encoding='utf-8',newline='\n')
    return manifest

if __name__=='__main__':
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--source',required=True,type=Path)
    parser.add_argument('--output',type=Path,default=Path('Asset/Brotato'))
    parser.add_argument('--catalog-output',type=Path,default=Path('Module/Brotato/Public'))
    args=parser.parse_args(); result=import_art(args.source,args.output,args.catalog_output)
    for record in result['assets']: print(record['image'],record['source_sprite'],record['size'])
