#!/usr/bin/env python3
"""Import recovered enemy sprites for newly designed gameplay; source stays read-only."""
import argparse
import json
import math
from pathlib import Path
from PIL import Image
from import_brotato_assets import read_guid, sha256, sprite_data


def import_art(source, output, catalog_output):
    source = source.resolve(strict=True)
    output, catalog_output = output.resolve(), catalog_output.resolve()
    for destination in (output, catalog_output):
        if destination == source or source in destination.parents:
            raise ValueError('Output must be outside the read-only Unity source project')
    assets = source / 'Assets'
    textures = {read_guid(p): p.with_suffix('') for p in sorted((assets/'Texture2D').glob('*.png.meta'))}
    records, crops = [], []
    for name, original in [('enemy_fast', '40002'), ('enemy_armored', '40003'),
                           ('enemy_ranged', '40004'), ('enemy_charger', '40005'), ('enemy_elite', '40006'), ('enemy_boss', '40020'),
                           ('enemy_healer', '40007'), ('enemy_summoner', '40008')]:
        sprite = assets / 'Sprite' / (original + '.asset')
        data = sprite_data(sprite)
        texture = textures[data['texture_guid']]
        with Image.open(texture) as image:
            image = image.convert('RGBA')
            x, y, width, height = data['unity_rect_xywh']
            box = (math.floor(x), image.height-math.ceil(y+height), math.ceil(x+width), image.height-math.floor(y))
            if not (0 <= box[0] < box[2] <= image.width and 0 <= box[1] < box[3] <= image.height):
                raise ValueError('Sprite rectangle is outside its texture')
            crop = image.crop(box)
            if not crop.getchannel('A').getbbox(): raise ValueError('Transparent enemy Sprite')
        records.append(dict(image=name, source_sprite=sprite.relative_to(source).as_posix(),
            source_texture=texture.relative_to(source).as_posix(), sprite_guid=read_guid(sprite.with_suffix('.asset.meta')),
            inputs=[dict(path=p.relative_to(source).as_posix(), sha256=sha256(p)) for p in
                    (sprite, sprite.with_suffix('.asset.meta'), texture, texture.with_suffix('.png.meta'))],
            **data, size=[width/data['pixels_per_unit'],height/data['pixels_per_unit']],
            crop_top_left_ltrb=list(box), output=name+'.png'))
        crops.append(crop)
    output.mkdir(parents=True,exist_ok=True); catalog_output.mkdir(parents=True,exist_ok=True)
    for record, crop in zip(records,crops):
        crop.save(output/record['output'],format='PNG',optimize=False)
        record['output_sha256'] = sha256(output/record['output'])
    manifest=dict(format_version=1, scope='Original art for newly designed enemy roles and boss; these roles are not recovered source AI.',assets=records)
    (output/'enemy_content_manifest.json').write_text(json.dumps(manifest,ensure_ascii=False,indent=2)+'\n',encoding='utf-8',newline='\n')
    def vec(values):
        return '{'+', '.join(format(v,'.9g')+('f' if '.' in format(v,'.9g') or 'e' in format(v,'.9g') else '.f') for v in values)+'}'
    header=['#pragma once','// Generated by tools/import_brotato_enemy_art.py; do not edit.','#include <array>','#include <glm/glm.hpp>',
            'namespace Brotato {','struct EnemyArt { glm::vec2 size, pivot; };',f'inline const std::array<EnemyArt, {len(records)}> ExtraEnemyArt{{{{']
    header += ['    {'+vec(r['size'])+', '+vec(r['unity_pivot_xy'])+'}, // '+r['image'] for r in records]
    header += ['}};','} // namespace Brotato','']
    (catalog_output/'enemy_art_catalog.h').write_text('\n'.join(header),encoding='utf-8',newline='\n')
    return manifest


if __name__=='__main__':
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--source',required=True,type=Path)
    parser.add_argument('--output',type=Path,default=Path('Asset/Brotato'))
    parser.add_argument('--catalog-output',type=Path,default=Path('Module/Brotato/Public'))
    args=parser.parse_args()
    result=import_art(args.source,args.output,args.catalog_output)
    for record in result['assets']: print(record['image'],record['source_sprite'],record['size'])
